### ISSUE TITLE
Compilation issue of 'strace.stp' file in Linux Machines

### ISSUE THREAD

**Issue by Sanghyun-Hong** [cuckoosandbox/cuckoo#1375]
Using Ubuntu12.04 as a virtual machine for analysis, I tried to compile the `strace.stp` file with the commands below:

```
// remove '%' after the variable names 'thread_argstr / thread_time'
sudo stap -r $(uname -r) strace.stp -m stap_cuckoo -v
```

However, it fails in the compilation step like below. I wonder what I did incorrectly.

```
Pass 1: parsed user script and 76 library script(s) using 92920virt/22980res/2644shr kb, in 120usr/10sys/131real ms.
Pass 2: analyzed script: 883 probe(s), 121 function(s), 27 embed(s), 7 global(s) using 102220virt/31180res/3736shr kb, in 270usr/170sys/440real ms.
Pass 3: translated to C into "/tmp/stap4dn9Ax/stap_cuckoo.c" using 102484virt/31440res/3884shr kb, in 170usr/20sys/189real ms.
In file included from /usr/share/systemtap/runtime/runtime.h:127:0,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:59:
/usr/share/systemtap/runtime/alloc.c: In function ‘_stp_kmalloc’:
/usr/share/systemtap/runtime/alloc.c:272:2: error: implicit declaration of function ‘kmalloc’ [-Werror=implicit-function-declaration]
/usr/share/systemtap/runtime/alloc.c:272:6: error: assignment makes pointer from integer without a cast [-Werror]
/usr/share/systemtap/runtime/alloc.c: In function ‘_stp_kzalloc’:
/usr/share/systemtap/runtime/alloc.c:322:2: error: implicit declaration of function ‘kzalloc’ [-Werror=implicit-function-declaration]
/usr/share/systemtap/runtime/alloc.c:322:6: error: assignment makes pointer from integer without a cast [-Werror]
/usr/share/systemtap/runtime/alloc.c: In function ‘_stp_kmalloc_node’:
/usr/share/systemtap/runtime/alloc.c:418:2: error: implicit declaration of function ‘kmalloc_node’ [-Werror=implicit-function-declaration]
/usr/share/systemtap/runtime/alloc.c:418:6: error: assignment makes pointer from integer without a cast [-Werror]
/usr/share/systemtap/runtime/alloc.c: In function ‘_stp_kfree’:
/usr/share/systemtap/runtime/alloc.c:432:2: error: implicit declaration of function ‘kfree’ [-Werror=implicit-function-declaration]
In file included from /usr/share/systemtap/runtime/transport/transport.c:53:0,
                 from /usr/share/systemtap/runtime/print.c:18,
                 from /usr/share/systemtap/runtime/runtime.h:128,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:59:
/usr/share/systemtap/runtime/transport/relay_v2.c: In function ‘__stp_relay_create_buf_file_callback’:
/usr/share/systemtap/runtime/transport/relay_v2.c:237:24: error: incompatible types when assigning to type ‘kuid_t’ from type ‘uid_t’
/usr/share/systemtap/runtime/transport/relay_v2.c:238:24: error: incompatible types when assigning to type ‘kgid_t’ from type ‘gid_t’
/usr/share/systemtap/runtime/transport/relay_v2.c: In function ‘_stp_transport_data_fs_init’:
/usr/share/systemtap/runtime/transport/relay_v2.c:306:47: error: incompatible types when assigning to type ‘kuid_t’ from type ‘uid_t’
/usr/share/systemtap/runtime/transport/relay_v2.c:307:47: error: incompatible types when assigning to type ‘kgid_t’ from type ‘gid_t’
In file included from /usr/share/systemtap/runtime/transport/transport.c:54:0,
                 from /usr/share/systemtap/runtime/print.c:18,
                 from /usr/share/systemtap/runtime/runtime.h:128,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:59:
/usr/share/systemtap/runtime/transport/debugfs.c: In function ‘_stp_register_ctl_channel_fs’:
/usr/share/systemtap/runtime/transport/debugfs.c:51:32: error: incompatible types when assigning to type ‘kuid_t’ from type ‘uid_t’
/usr/share/systemtap/runtime/transport/debugfs.c:52:32: error: incompatible types when assigning to type ‘kgid_t’ from type ‘gid_t’
In file included from /usr/share/systemtap/runtime/print.c:18:0,
                 from /usr/share/systemtap/runtime/runtime.h:128,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:59:
/usr/share/systemtap/runtime/transport/transport.c: In function ‘_stp_transport_init’:
/usr/share/systemtap/runtime/transport/transport.c:244:11: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
/usr/share/systemtap/runtime/transport/transport.c:245:11: error: incompatible types when assigning to type ‘gid_t’ from type ‘kgid_t’
In file included from /usr/share/systemtap/runtime/vma.c:18:0,
                 from /usr/share/systemtap/runtime/sym.c:16,
                 from /usr/share/systemtap/runtime/runtime.h:138,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:59:
/usr/share/systemtap/runtime/task_finder_vma.c: In function ‘__stp_tf_vma_get_free_entry’:
/usr/share/systemtap/runtime/task_finder_vma.c:87:47: error: macro "hlist_for_each_entry" passed 4 arguments, but takes just 3
/usr/share/systemtap/runtime/task_finder_vma.c:87:2: error: ‘hlist_for_each_entry’ undeclared (first use in this function)
/usr/share/systemtap/runtime/task_finder_vma.c:87:2: note: each undeclared identifier is reported only once for each function it appears in
/usr/share/systemtap/runtime/task_finder_vma.c:87:49: error: expected ‘;’ before ‘{’ token
/usr/share/systemtap/runtime/task_finder_vma.c: In function ‘__stp_tf_get_vma_map_entry_internal’:
/usr/share/systemtap/runtime/task_finder_vma.c:125:47: error: macro "hlist_for_each_entry" passed 4 arguments, but takes just 3
/usr/share/systemtap/runtime/task_finder_vma.c:125:2: error: ‘hlist_for_each_entry’ undeclared (first use in this function)
/usr/share/systemtap/runtime/task_finder_vma.c:125:49: error: expected ‘;’ before ‘{’ token
/usr/share/systemtap/runtime/task_finder_vma.c:132:1: error: no return statement in function returning non-void [-Werror=return-type]
/usr/share/systemtap/runtime/task_finder_vma.c: In function ‘stap_find_vma_map_info’:
/usr/share/systemtap/runtime/task_finder_vma.c:233:47: error: macro "hlist_for_each_entry" passed 4 arguments, but takes just 3
/usr/share/systemtap/runtime/task_finder_vma.c:233:2: error: ‘hlist_for_each_entry’ undeclared (first use in this function)
/usr/share/systemtap/runtime/task_finder_vma.c:233:49: error: expected ‘;’ before ‘{’ token
/usr/share/systemtap/runtime/task_finder_vma.c: In function ‘stap_find_vma_map_info_user’:
/usr/share/systemtap/runtime/task_finder_vma.c:274:47: error: macro "hlist_for_each_entry" passed 4 arguments, but takes just 3
/usr/share/systemtap/runtime/task_finder_vma.c:274:2: error: ‘hlist_for_each_entry’ undeclared (first use in this function)
/usr/share/systemtap/runtime/task_finder_vma.c:274:49: error: expected ‘;’ before ‘{’ token
/usr/share/systemtap/runtime/task_finder_vma.c: In function ‘stap_drop_vma_maps’:
/usr/share/systemtap/runtime/task_finder_vma.c:305:62: error: macro "hlist_for_each_entry_safe" passed 5 arguments, but takes just 4
/usr/share/systemtap/runtime/task_finder_vma.c:305:9: error: ‘hlist_for_each_entry_safe’ undeclared (first use in this function)
/usr/share/systemtap/runtime/task_finder_vma.c:305:64: error: expected ‘;’ before ‘{’ token
In file included from include/linux/textsearch.h:8:0,
                 from include/linux/skbuff.h:28,
                 from include/linux/netlink.h:6,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:115:
include/linux/slab.h: At top level:
include/linux/slab.h:142:6: error: conflicting types for ‘kfree’ [-Werror]
/usr/share/systemtap/runtime/alloc.c:432:2: note: previous implicit declaration of ‘kfree’ was here
In file included from include/linux/textsearch.h:8:0,
                 from include/linux/skbuff.h:28,
                 from include/linux/netlink.h:6,
                 from /tmp/stap4dn9Ax/stap_cuckoo.c:115:
include/linux/slab.h:441:30: error: conflicting types for ‘kmalloc’
/usr/share/systemtap/runtime/alloc.c:272:8: note: previous implicit declaration of ‘kmalloc’ was here
include/linux/slab.h:481:30: error: conflicting types for ‘kmalloc_node’
/usr/share/systemtap/runtime/alloc.c:418:8: note: previous implicit declaration of ‘kmalloc_node’ was here
include/linux/slab.h:633:21: error: conflicting types for ‘kzalloc’
/usr/share/systemtap/runtime/alloc.c:322:8: note: previous implicit declaration of ‘kzalloc’ was here
cc1: all warnings being treated as errors
make[1]: *** [/tmp/stap4dn9Ax/stap_cuckoo.o] Error 1
make: *** [_module_/tmp/stap4dn9Ax] Error 2
Warning: make exited with status: 2
Pass 4: compiled C into "stap_cuckoo.ko" in 7230usr/1300sys/8629real ms.
Pass 4: compilation failed.  Try again with another '--vp 0001' option.
```

**Comment by doomedraven** [comment]
first of all why ubuntu 12.04? i had problems compile it in old kernels, but in ubuntu 16.04 it works just fine, see result here https://linux.huntingmalware.com/analysis/1/behavior/

**Comment by Sanghyun-Hong** [comment]
@doomedraven I would like to run an exploit which is only reproduced in the old version of kernel. Could I know the oldest version where the 'strace.stp' file can be compiled?

**Comment by doomedraven** [comment]
i haven't tested it with all kernel, but basically, I had some fails on kernel it for <v4, maybe some of v3 will work, but that which I tested didn't work, i don't remember versions of v3 which i had tested

**Comment by paradise6** [comment]
i have tried  to compile in ubuntu 16.04, but still got the error
sudo stap -r $(uname -r) strace.stp -m stap_ -v


all warnings being treated as errors
scripts/Makefile.build:289: recipe for target '/tmp/stapWvq42J/stap__src.o' failed
make[1]: *** [/tmp/stapWvq42J/stap__src.o] Error 1
Makefile:1491: recipe for target '_module_/tmp/stapWvq42J' failed
make: *** [_module_/tmp/stapWvq42J] Error 2
WARNING: kbuild exited with status: 2
Pass 4: compiled C into "stap_.ko" in 6860usr/750sys/8346real ms.
Pass 4: compilation failed.  [man error::pass4]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.

**Comment by doomedraven** [comment]
did you install dependencies? because it works just fine for me, but that is only compile on x32 not x64

**Comment by jbremer** [comment]
Any progress here guys? Any additional steps that we can add to our documentation on this matter?

**Comment by doomedraven** [comment]
Provide versions of ubuntu, stap etc, to verify with my setup, bcz it worked just fine with steps which i specified in documentation

**Comment by 0x89f** [comment]
I had the same issue as poster. I got this to work by uninstalling the Ubuntu distro version of Systemtap  (2.9) and installed version 3.1 from source. Not sure why that is the solution.

**Comment by doomedraven** [comment]
did you add the sources for the systemtap for 17.04? and installed from them? it worked just fine for me on x32/x64/arm

**Comment by 0x89f** [comment]
My guest is a 16.04 system and I needed the sources. I haven't tried with 17.04 yet

**Comment by doomedraven** [comment]
RTM! only 17.04 suggested you will need to patch systemtaps scripts by yourself for correct working https://github.com/cuckoosandbox/cuckoo/blob/master/docs/book/installation/guest/linux.rst

**Comment by 0x89f** [comment]
I saw that instruction but It did not work for me. I would not go out of my way to attempt to patch the scripts if I did not have to. Behavioural analysis did not work and I tried KVM and Virtualbox. It is working for me now using KVM. I assumed it was a mistake in documentation because I also saw this link below after.

http://docs.cuckoosandbox.org/en/latest/installation/guest/linux/

**Comment by doomedraven** [comment]
that is all documentation, they need to update and accept my improvements for one which i point you.

use link which i pointed you + ubuntu 17.04 and everything will works, say not working without log, or error or what ever don't help to solve/help you sorry

**Comment by jbremer** [comment]
Old documentation indeed. I'll check if there are any pending Linux Analyzer docs PRs, @doomedraven. Closing this issue as resolved.
