### ISSUE TITLE
ERROR: Missing dependency: No module named requests

### ISSUE THREAD

**Issue by plaxer** [cuckoosandbox/cuckoo#1418]
I get this error after running `sudo python cuckoo.py` in the `/opt/cuckoo` directory.

Here's a preview of the cuckoo directory:

```
total 56
drwxr-xr-x  2 root root 4096 Nov  5 03:20 agent
drwxr-xr-x  6 root root 4096 Nov  5 03:20 analyzer
drwxr-xr-x  2 root root 4096 Apr 15 15:54 conf
-rwxr-xr-x  1 root root 4663 Nov  5 03:20 cuckoo.py
drwxr-xr-x 10 root root 4096 Nov  5 03:20 data
drwxr-xr-x  4 root root 4096 Nov  5 03:20 distributed
drwxr-xr-x  4 root root 4096 Nov  5 03:21 docs
drwxr-xr-x  3 root root 4096 Apr 15 15:55 lib
drwxr-xr-x  7 root root 4096 Nov  5 03:22 modules
-rw-r--r--  1 root root  964 Nov  5 03:20 README.md
-rw-r--r--  1 root root  623 Nov  5 03:20 requirements.txt
drwxr-xr-x  4 root root 4096 Nov  5 03:20 utils
drwxr-xr-x  9 root root 4096 Nov  5 03:20 web
```
What exactly am I doing wrong? I followed the installation guide

**Comment by doomedraven** [comment]
first of all upgrade to cuckoo v2 which doesn't have anymore this structure and installs all deps automatically, in old version `sudo pip install -r requirements.txt`

**Comment by plaxer** [comment]
@doomedraven Will I have to reconfigure cuckoo again after doing this? It's currently downloading all dependencies.

**Comment by jbremer** [comment]
@plaxer You can either reconfigure or "import" your old setup into the new one after upgrading to 2.0.0, see also https://cuckoo.sh/docs/installation/upgrade.html

**Comment by plaxer** [comment]
@jbremer Hey, what about these errors I'm getting after following @doomedraven 's instructions?

```
/opt/cuckoo$ sudo python cuckoo.py 
Traceback (most recent call last):
  File "cuckoo.py", line 18, in <module>
    from lib.cuckoo.common.utils import exception_message
  File "/opt/cuckoo/lib/cuckoo/common/utils.py", line 32, in <module>
    import bs4
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

I have no idea what's going on

**Comment by jbremer** [comment]
Usually `pip uninstall html5lib beautifulsoup4 ; pip install -U beautifulsoup4` should do the trick. Could you share the output of `pip freeze` with me though?

**Comment by plaxer** [comment]
@jbremer I deleted the cuckoo folder and started a fresh installation. 

After following every procedure, [I've gotten to this page of the guide.](https://cuckoo.sh/docs/installation/host/cwd.html) After running `$ cuckoo -d`, I got the following output;

```
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo==2.0.1', 'console_scripts', 'cuckoo')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/__init__.py", line 10, in <module>
    __file__, "cuckoo.processing", globals(), Processing
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 39, in enumerate_plugins
    "%s.%s" % (module_prefix, module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 22, in <module>
    import volatility.plugins.malware.apihooks as apihooks
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/malware/apihooks.py", line 162, in <module>
    class Hook(object):
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/malware/apihooks.py", line 169, in Hook
    decode_bits = distorm3.Decode32Bits):
NameError: name 'distorm3' is not defined
```
I don't understand why everything seems to be broken for me, I'm getting really frustrated as I've been on this for over a week now. I just can't get cuckoo to work and I need this for my dissertation.

**Comment by jbremer** [comment]
That's just a failure on the volatility side. You have to `pip install distorm3`, as per their documentation (I assume).

**Comment by plaxer** [comment]
@jbremer Thanks for seeing me through this. I'm gonna submit a sample and update you.

**Comment by plaxer** [comment]
@jbremer With this new version, do I need to run virtualbox using `gksudo` or just as normal user to get the VM to interact with cuckoo?

**Comment by jbremer** [comment]
You should be running both virtualbox & cuckoo as a regular user.

**Comment by plaxer** [comment]
@jbremer okay then but prior to your response, I ran sudo cuckoo after creating the cuckoo opt directory and here's my output:

```
  _____________________________________/\/\_______________________________
  ___/\/\/\/\__/\/\__/\/\____/\/\/\/\__/\/\__/\/\____/\/\/\______/\/\/\___
  _/\/\________/\/\__/\/\__/\/\________/\/\/\/\____/\/\__/\/\__/\/\__/\/\_
  _/\/\________/\/\__/\/\__/\/\________/\/\/\/\____/\/\__/\/\__/\/\__/\/\_
  ___/\/\/\/\____/\/\/\/\____/\/\/\/\__/\/\__/\/\____/\/\/\______/\/\/\___
  ________________________________________________________________________

 Cuckoo Sandbox 2.0.1
 www.cuckoosandbox.org
 Copyright (c) 2010-2017

2017-04-15 18:28:33,689 [cuckoo.core.startup] WARNING: Unable to import yara (please compile from sources)
2017-04-15 18:28:33,690 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-15 18:28:34,043 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-15 18:28:34,066 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
```
What can I do to get rid of this error: `WARNING: Unable to import yara (please compile from sources)`

**Comment by jbremer** [comment]
It's an optional feature, you can ignore it (unless you intend to use Yara rules of course). And also, the warning literally says what to do - install yara.. ;-)

**Comment by plaxer** [comment]
@jbremer SO how do I send the sample to the VM? Previous version of cuckoo used `submit.py` in the `/opt/cuckoo/utils` but I can't seem to find how to submit the sample in this version.

Here is the cuckoo directory:

```
total 132
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 17:44 agent
drwxr-sr-x 6 plaxer plaxer  4096 Apr 15 17:44 analyzer
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 18:20 conf
-rw-r--r-- 1 plaxer plaxer 65536 Apr 15 18:28 cuckoo.db
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 17:44 distributed
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 17:44 elasticsearch
-rw-r--r-- 1 plaxer plaxer  2222 Apr  9 15:46 gatherer.py
-rw-r--r-- 1 plaxer plaxer  163 Apr  9 15:46 __init__.py
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 18:07 log
-rw-r--r-- 1 plaxer plaxer   335 Apr  9 15:46 mitm.py
drwxr-sr-x 3 plaxer plaxer  4096 Apr 15 17:44 monitor
drwxr-sr-x 7 plaxer plaxer  4096 Apr 15 17:44 signatures
drwxr-sr-x 5 plaxer plaxer  4096 Apr 15 17:44 storage
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 17:44 supervisord
-rw-r--r-- 1 plaxer plaxer  867 Apr 15 18:04 supervisord.conf
drwxr-sr-x 2 plaxer plaxer  4096 Apr 15 17:44 web
drwxr-sr-x 5 plaxer plaxer  4096 Apr 15 17:44 yara

```

Please tell me how to submit the sample.

**Comment by doomedraven** [comment]
Also cuckoo --help do magic ;)

**Comment by plaxer** [comment]
@doomedraven @jbremer hey guys, how do I add a user "cuckoo" to the 'libvirtd' group? It tells me `usermod: group 'libvirtd' does not exist`. I'm still fairly new to linux so don't know how to proceed from here. I've searched online and installed every dependency but no luck.

**Comment by doomedraven** [comment]
`groupadd libvirtd && usermod -G libvirtd -a cuckoo`

**Comment by plaxer** [comment]
@doomedraven 
Input:
`$ groupadd libvirtd && usermod -G libvirtd -a cuckoo`

```
groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
```

WIth sudo 
```
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
```
Still no luck :(

**Comment by doomedraven** [comment]
well from here you should start googling errors as they totally not related to cuckoo, that may be different from distro to distro

for example
https://superuser.com/questions/296373/cannot-lock-etc-passwd-try-again-later

**Comment by plaxer** [comment]
I worked mate, cheers.

**Comment by doomedraven** [comment]
so that solved it ? :)

**Comment by plaxer** [comment]
@doomedraven yeah, hopefully I can finally get everything to work. So just one final question, everything from the installation of cuckoo to the creation of the VM will be done using the cuckoo user right?

**Comment by doomedraven** [comment]
well it will install cuckoo and cuckoo's python libraries, but you should follow https://cuckoo.sh/docs/index.html as there many other steps which you should do manually to install and configure many things

**Comment by plaxer** [comment]
@doomedraven okay, cool. My problem was using my main user and gksudo to run the VM as I saw on some other issue thread that cuckoo can only interact with the VM if it's running as root.

**Comment by doomedraven** [comment]
never use it with sudo, people who don't read manuals run it as root, and then can be pwned, not by cuckoo vulns, but that says a lot about their hardening skills :D, only rooter if you use it, but it has option `--sudo`

**Comment by plaxer** [comment]
Fair enough. I'm still learning how to get better and more familiar with linux.

**Comment by doomedraven** [comment]
my advice, less root, more hardening :)
and you can play with`linux cuckoo`samples here also https://linux.huntingmalware.com/dashboard/ :P

**Comment by plaxer** [comment]
Thanks, will have a look later when I'm done with my work.

**Comment by jbremer** [comment]
@plaxer We've just released an alpha release, which you can get with `pip install cuckoo==2.0.2a2`, containing a fix for the issue here. Please let me know if it also works on your side. This will be part of the upcoming `2.0.2` release.

**Comment by plaxer** [comment]
@Jbremer cheers mate, will be sure to install and provide feedback once I have access to my laptop.

**Comment by jbremer** [comment]
Didn't get any feedback so assuming all went well. Feel free to reopen if this was not the case.
Closing as resolved.

**Comment by arnydo** [comment]
With my limited knowledge on Supervisord I attempted to add the following to the supervisord.conf (see the "cuckoo-rooter" section). I assume there is going to be a permission issue going this route? Ideas?

```
[supervisord]
logfile = /home/cuckoo/.cuckoo/supervisord/log.log
pidfile = /home/cuckoo/.cuckoo/supervisord/pidfile
user = cuckoo

[supervisorctl]
serverurl = unix:///home/cuckoo/.cuckoo/supervisord/unix.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file = /home/cuckoo/.cuckoo/supervisord/unix.sock

[program:cuckoo-rooter]
command = cuckoo rooter
stdout_logfile=/home/cuckoo/.cuckoo/log/rooter.log
user = root
autostart = true
autorestart = true

[program:cuckoo-daemon]
command = cuckoo -d -m 10000
user = cuckoo
startsecs = 30
autorestart = true

[program:cuckoo-process]
command = cuckoo process p%(process_num)d
process_name = cuckoo-process_%(process_num)d
numprocs = 4
user = cuckoo
autorestart = true

[group:cuckoo]
programs = cuckoo-rooter, cuckoo-daemon, cuckoo-process

[program:distributed]
command = python -m cuckoo.distributed.worker
user = cuckoo
autostart = false
autorestart = true
environment = CUCKOO_APP="worker",CUCKOO_CWD="/home/cuckoo/.cuckoo"
```

**Comment by alaaaaaaaaaa** [comment]
I get this error after running $cuckoo via terminal 
Here's the cuckoo output:
"
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/__init__.py", line 10, in <module>
    __file__, "cuckoo.processing", globals(), Processing
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at memory.py: No module named privileges. Please review its contents and/or validity!  "

cuckoo was worked smoothly until i had configure volatility, i had install distorm3 but that doesn't solve the problem.

**Comment by doomedraven** [comment]
check the memory.conf maybe any typo or that plugin not available in your version

**Comment by alaaaaaaaaaa** [comment]
i check it, its normal!

**Comment by doomedraven** [comment]
if that would be normal that error wouldn't popuped :P

post your vol version, memory conf and check if you have
`/usr/local/lib/python2.7/dist-packages/volatility/plugins/privileges.py` or where your vol installed

**Comment by alaaaaaaaaaa** [comment]
volatility version 2.2
no privileges.py file!

**Comment by jbremer** [comment]
Perhaps you could consider not installing a 5 year old version of Volatility ;-)
http://www.volatilityfoundation.org/22

**Comment by doomedraven** [comment]
that of installing from pip i think, @jbremer add vol minimal version to check as with the rest of plugins 2.5 should be fine i think ;)

**Comment by alaaaaaaaaaa** [comment]
vol 2.5 doesn't support 2.10 linux kernal 
[4.10.0-33-generic]

**Comment by doomedraven** [comment]
well that isn't a cuckoo problem, you just need to generate linux kernel profile for 2.10 linux and add it to your vol, see vol wiki

**Comment by doomedraven** [comment]
or disable unsuported plugins in memory.conf

**Comment by alaaaaaaaaaa** [comment]
i think the error because  No module named privileges in

/usr/local/lib/python2.7/dist-packages/volatility/plugins/privileges.py

**Comment by alaaaaaaaaaa** [comment]
i mean no privileges.py modules

**Comment by doomedraven** [comment]
just disable that plugin in memory.conf, and the rst if similar error will raised

**Comment by alaaaaaaaaaa** [comment]
All blugin is disabled now
And I had installed vol 2.6.
Still same error!

بتاريخ 2017/12/02 4:25 م، كتب "doomedraven" <notifications@github.com>:

**Comment by alaaaaaaaaaa** [comment]
it works now
thank you :)

**Comment by doomedraven** [comment]
;)

**Comment by marcusgowp** [comment]
I get this error after running $cuckoo -d
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/__init__.py", line 6, in <module>
    from cuckoo.core.plugins import enumerate_plugins
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 13, in <module>
    from cuckoo.common.config import config2
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/config.py", line 13, in <module>
    from cuckoo.common.objects import Dictionary
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/objects.py", line 19, in <module>
    from cuckoo.common.whitelist import is_whitelisted_domain
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/common/whitelist.py", line 7, in <module>
    from cuckoo.misc import cwd
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/misc.py", line 38, in <module>
    version = ".".join(pkg_resources.require("Cuckoo")[0].version.split(".")[:3])
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SQLAlchemy 1.2.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('sqlalchemy==1.0.8'), set(['Cuckoo']))
