### ISSUE TITLE
inetsim routing option errors

### ISSUE THREAD

**Issue by seanthegeek** [cuckoosandbox/cuckoo#1440]
When selecting the inetsim routing option, cuckoo geives the following errors, and the task never completes.
```

2017-04-20 10:28:26,883 [cuckoo.core.rooter] WARNING: Rooter returned error: remote_dns_forward() takes exactly 4 arguments (3 given)
2017-04-20 10:28:26,898 [cuckoo.core.guest] INFO: Starting analysis on guest (id=win7, ip=192.168.100.42)
2017-04-20 10:31:29,586 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-04-20 10:31:30,010 [cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 697, in run
    self.launch_analysis()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 621, in launch_analysis
    self.unroute_network()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/scheduler.py", line 360, in unroute_network
    str(cfg.resultserver.port))
AttributeError: 'Config' object has no attribute 'resultserver'
```

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/issues/1380

**Comment by jbremer** [comment]
Yeah, inetsim isn't working yet, but @doomedraven is working on it as you can see :)

**Comment by doomedraven** [comment]
test this PR and feedback is welcome https://github.com/cuckoosandbox/cuckoo/pull/1435

**Comment by seanthegeek** [comment]
@doomedraven @jbremer Hmm, now this is odd.

My usual hack for getting inetsim working in legacy Cuckoo isn't working Cuckoo 2.0.1.

I have a script that runs the following commands at boot:

```bash
VIRBR_IP="192.168.100.1"
INETSIM_DNS_PORT="5342"
VIRBR_DEV="virbr0"

# Redirect libvirt VM DNS quires to inetsim's DNS port
/sbin/iptables -t nat -C  PREROUTING -d $VIRBR_IP -p udp --dport 53 -j REDIRECT --to-ports $INETSIM_DNS_PORT >/dev/null 2>&1
if [ $? -ne 0 ]; then
    /sbin/iptables -t nat -I PREROUTING -d $VIRBR_IP -p udp --dport 53 -j REDIRECT --to-ports $INETSIM_DNS_PORT
fi

# Allow inetsim to accept traffic for any IP address
/sbin/iptables -t nat -C PREROUTING -i $VIRBR_DEV -j REDIRECT >/dev/null 2>&1
if [ $? -ne 0 ]; then
    /sbin/iptables -t nat -A PREROUTING -i $VIRBR_DEV -j REDIRECT
fi

```

If I use the VM myself, outside of a Cuckoo analysis, this works file, and it worked fine in Cuckoo 2.0 RC2 and earlier, but when this is used in a 2.0.1 analysis with routing set to None, DNS resolution fails. Rooter shouldn't be doing anything when Route is set to None, right? Any ideas what is causing this. I suspect if I can fix this, I can also get VPN connectivity working for Cuckoo, which is doing the same thing.

**Comment by doomedraven** [comment]
it was the same on my side, is why i did fixes, check iptables of inetsim_enable

**Comment by seanthegeek** [comment]
@doomedraven I'll try it out. I guess VPN still worked for you regardless? I'll create a separate issue with details of my config to see  what could be wrong.

**Comment by doomedraven** [comment]
i didn't test vpn with 2.0.1 but with rc2 it works fine if you pass the args which i specified in that issue

```
#!/usr/bin/python
import os
import subprocess

IP_ROUTE_TABLES='/etc/iproute2/rt_tables'

if __name__ == '__main__':
	config_name = os.environ.get('config')
	local_ip = os.environ.get('ifconfig_local')
	vpn_gateway = os.environ.get('route_vpn_gateway')
	common_name = os.environ.get('common_name')
	dev = os.environ.get('dev')

	ip_table = common_name

	print 'ip rule add from {} table {}'.format(local_ip, ip_table)
	print 'ip route add default via {} dev {} table {}'.format(vpn_gateway, dev, ip_table)
    subprocess.call(['ip', 'rule', 'add', 'from', local_ip, 'table', ip_table])
    subprocess.call(['ip', 'route', 'add', 'default', 'via', vpn_gateway, 'dev', dev, 'table', ip_table])
```

`openvpn --log-append /var/log/openvpn_logs.log --config X.ovpn --script-security 2 --route-noexec --route-up route.py`

it will set routes autoamtically

**Comment by jbremer** [comment]
I have tested VPNs as working in 2.0.0+, although I believe there was an issue on that somewhere?

**Comment by doomedraven** [comment]
yup, somwhere in issues :D

**Comment by seanthegeek** [comment]
@jbremer #1367?

@doomedraven So rooter does not create the default route itself? That explains why it wasn't working. Any suggestions on how I can determine the VPN gateway and local IP address via python? That might change at any time based on the VPN provider's config...

**Comment by jbremer** [comment]
It does create the routes. Not sure if you need a default route if you explicitly route a VM through an interface?

**Comment by doomedraven** [comment]
in my case in all what i tested i'm getting them from provider and it set as env vars, is why i have print there to see what it applies.

well in my case it creates but it send whole traffic to vpn so i lose ssh connection, is why i do that

**Comment by seanthegeek** [comment]
@jbremer I don't think a default route is needed. I don't want it anyway, because then I loose access to SSH and the web UI. I had to add a route for my local network to the VPN config to stop it from blocking local traffic.

```
openvpn
client

dev tun0

# Route LAN traffic through local gateway
route 10.0.0.0 255.0.0.0 10.205.2.1

proto udp

remote us.[REDACTED].net 1300
cipher AES-256-CBC

# Tunnel IPv6 traffic as well as IPv4
tun-ipv6

# Keep trying indefinitely to resolve the
# host name of the OpenVPN server.  Very useful
# on machines which are not permanently connected
# to the internet such as laptops.
resolv-retry infinite

# Most clients don't need to bind to
# a specific local port number.
nobind

# Try to preserve some state across restarts.
persist-key
persist-tun

# Enable compression on the VPN link.
comp-lzo

# Set log file verbosity.
verb 3

remote-cert-tls server

ping-restart 60

# Allow calling of built-in executables and user-defined scripts.
script-security 2

# Parses DHCP options from openvpn to update resolv.conf
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf

ping 10

ca ca.crt
cert [REDACTED].crt
key [REDACTED].key

crl-verify crl.pem

# Limit range of possible TLS cipher-suites
tls-cipher [REDACTED]
```

Connection log

```
Thu Apr 20 14:19:03 2017 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
Thu Apr 20 14:19:03 2017 OpenVPN 2.4.0 [git:master/2ff7b31604107f4e+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb  2 2017
Thu Apr 20 14:19:03 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Thu Apr 20 14:19:03 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Apr 20 14:19:03 2017 TCP/UDP: Preserving recently used remote address: [AF_INET][REDACTED]:1300
Thu Apr 20 14:19:03 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Apr 20 14:19:03 2017 UDP link local: (not bound)
Thu Apr 20 14:19:03 2017 UDP link remote: [AF_INET][REDACTED]:1300
Thu Apr 20 14:19:04 2017 TLS: Initial packet from [AF_INET][REDACTED]:1300, sid=c1cf29e4 def6d6ad
Thu Apr 20 14:19:04 2017 VERIFY WARNING: depth=1, unable to get certificate CRL: C=NA, ST=None, L=None, O=[REDACTED], CN=master.[REDACTED].net, emailAddress=info@[REDACTED].net
Thu Apr 20 14:19:04 2017 VERIFY WARNING: depth=2, unable to get certificate CRL: C=NA, ST=None, L=None, O=[REDACTED], CN=[REDACTED] CA, emailAddress=info@[REDACTED].net
Thu Apr 20 14:19:04 2017 VERIFY OK: depth=2, C=NA, ST=None, L=None, O=[REDACTED], CN=[REDACTED] CA, emailAddress=info@[REDACTED].net
Thu Apr 20 14:19:04 2017 VERIFY OK: depth=1, C=NA, ST=None, L=None, O=[REDACTED], CN=master.[REDACTED].net, emailAddress=info@[REDACTED].net
Thu Apr 20 14:19:04 2017 Validating certificate key usage
Thu Apr 20 14:19:04 2017 ++ Certificate has key usage  00a0, expects 00a0
Thu Apr 20 14:19:04 2017 VERIFY KU OK
Thu Apr 20 14:19:04 2017 Validating certificate extended key usage
Thu Apr 20 14:19:04 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Apr 20 14:19:04 2017 VERIFY EKU OK
Thu Apr 20 14:19:04 2017 VERIFY OK: depth=0, C=NA, ST=None, L=None, O=[REDACTED], CN=us16.[REDACTED].net, emailAddress=info@[REDACTED].net
Thu Apr 20 14:19:04 2017 Control Channel:[REDACTED]
Thu Apr 20 14:19:04 2017 [us16.[REDACTED].net] Peer Connection Initiated with [AF_INET][REDACTED]:1300
Thu Apr 20 14:19:05 2017 SENT CONTROL [us16.[REDACTED].net]: 'PUSH_REQUEST' (status=1)
Thu Apr 20 14:19:10 2017 SENT CONTROL [us16.[REDACTED].net]: 'PUSH_REQUEST' (status=1)
Thu Apr 20 14:19:15 2017 SENT CONTROL [us16.[REDACTED].net]: 'PUSH_REQUEST' (status=1)
Thu Apr 20 14:19:15 2017 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 10.14.0.1,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,route-gateway 10.14.0.1,topology subnet,ifconfig-ipv6 fdda:d0d0:cafe:1300::100b/64 fdda:d0d0:cafe:1300::,ifconfig 10.14.0.13 255.255.0.0,peer-id 11,cipher [REDACTED]'
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: --ifconfig/up options modified
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: route options modified
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: route-related options modified
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: peer-id set
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: adjusting link_mtu to 1625
Thu Apr 20 14:19:15 2017 OPTIONS IMPORT: data channel crypto options modified
Thu Apr 20 14:19:15 2017 Data Channel Encrypt: Cipher '[REDACTED]' initialized with 256 bit key
Thu Apr 20 14:19:15 2017 Data Channel Decrypt: Cipher '[REDACTED]' initialized with 256 bit key
Thu Apr 20 14:19:15 2017 ROUTE_GATEWAY 10.205.2.1/255.255.255.0 IFACE=ens192 HWADDR=[REDACTED]
Thu Apr 20 14:19:15 2017 GDG6: remote_host_ipv6=n/a
Thu Apr 20 14:19:15 2017 ROUTE6: default_gateway=UNDEF
Thu Apr 20 14:19:15 2017 TUN/TAP device tun0 opened
Thu Apr 20 14:19:15 2017 TUN/TAP TX queue length set to 100
Thu Apr 20 14:19:15 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=1
Thu Apr 20 14:19:15 2017 /sbin/ip link set dev tun0 up mtu 1500
Thu Apr 20 14:19:15 2017 /sbin/ip addr add dev tun0 10.14.0.13/16 broadcast 10.14.255.255
Thu Apr 20 14:19:15 2017 /sbin/ip -6 addr add fdda:d0d0:cafe:1300::100b/64 dev tun0
Thu Apr 20 14:19:15 2017 /etc/openvpn/update-resolv-conf tun0 1500 1553 10.14.0.13 255.255.0.0 init
dhcp-option DNS 10.14.0.1
Thu Apr 20 14:19:15 2017 /sbin/ip route add [REDACTED]/32 via 10.205.2.1
Thu Apr 20 14:19:15 2017 /sbin/ip route add 0.0.0.0/1 via 10.14.0.1
Thu Apr 20 14:19:15 2017 /sbin/ip route add 128.0.0.0/1 via 10.14.0.1
Thu Apr 20 14:19:15 2017 /sbin/ip route add 10.0.0.0/8 via 10.205.2.1
Thu Apr 20 14:19:15 2017 add_route_ipv6(::/2 -> fdda:d0d0:cafe:1300:: metric -1) dev tun0
Thu Apr 20 14:19:15 2017 /sbin/ip -6 route add ::/2 dev tun0
Thu Apr 20 14:19:15 2017 add_route_ipv6(4000::/2 -> fdda:d0d0:cafe:1300:: metric -1) dev tun0
Thu Apr 20 14:19:15 2017 /sbin/ip -6 route add 4000::/2 dev tun0
Thu Apr 20 14:19:15 2017 add_route_ipv6(8000::/2 -> fdda:d0d0:cafe:1300:: metric -1) dev tun0
Thu Apr 20 14:19:15 2017 /sbin/ip -6 route add 8000::/2 dev tun0
Thu Apr 20 14:19:15 2017 add_route_ipv6(c000::/2 -> fdda:d0d0:cafe:1300:: metric -1) dev tun0
Thu Apr 20 14:19:15 2017 /sbin/ip -6 route add c000::/2 dev tun0
Thu Apr 20 14:19:15 2017 Initialization Sequence Completed
```

`/etc/iproute2/rt_tables`

```
# reserved values
#
255     local
254     main
253     default
0       unspec
#
# local
#
#1      inr.ruhep
201 tun0
```

`$CWD/conf/routing.conf`

```
[vpn]
# Are VPNs enabled?
enabled = yes

# Comma-separated list of the available VPNs.
vpns = us


[us]
# Name of this VPN. The name is represented by the filepath to the
# configuration file, e.g., cuckoo would represent /etc/openvpn/cuckoo.conf
# Note that you can't assign the names "none" and "internet" as those would
# conflict with the routing section in cuckoo.conf.
name = us

# The description of this VPN which will be displayed in the web interface.
# Can be used to for example describe the country where this VPN ends up.
description = United States

# The tun device hardcoded for this VPN. Each VPN *must* be configured to use
# a hardcoded/persistent tun device by explicitly adding the line "dev tunX"
# to its configuration (e.g., /etc/openvpn/vpn1.conf) where X in tunX is a
# unique number between 0 and your lucky number of choice.
interface = tun0

# Routing table name/id for this VPN. If table name is used it *must* be
# added to /etc/iproute2/rt_tables as "<id> <name>" line (e.g., "201 tun0").
# ID and name must be unique across the system (refer /etc/iproute2/rt_tables
# for existing names and IDs).
rt_table = tun0
```

Anything obviously wrong here.? The VPN stays up, and traffic all internet traffic on the host (e.g. curl).

**Comment by jbremer** [comment]
The InetSim PR has been merged, please test it and provide us with feedback. Please leave your comments in #1435. If something else has been discussed in this thread that I missed, but that's important in one way or another, please reopen the issue with an additional comment or copy the comment / issue / whatever to #1435.
I'll be closing this issue now. In #1435 I'll be announcing when a new alpha or stable release is out in which you may find the InetSim working once again. Thanks again for the feedback & sorry once more for the delay on our side.
Ping @seanthegeek.
